---
- name: vaza apache
  hosts: docker
  remote_user: root
  tasks:
   - name: para o menino apache
     service:
      name: apache2
      state: stopped
 
   - name: tchau apache
     apt:
      name: apache2
      state: absent
